
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: {{.Values.todoapp.namespace}}
spec:
  volumeName: {{.Values.todoapp.pvc.volumeName}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.todoapp.pv.storageCapacity}}