apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-{{ .Values.todoapp.pv.volumeName }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{.Values.todoapp.pv.storageCapacity}}
  hostPath:
    path: /data/
