
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-data
  namespace: {{.Values.todoapp.namespace}}
spec:
  volumeName: {{ .Chart.Name }}-{{ .Values.todoapp.pv.volumeName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.todoapp.pvc.storageCapacity}}